import { z } from 'zod'

export class agentSchema {
    postCreateAgent() {
        return z.object({
            selfie_image_url: z.null(),
            phone_number: z.string(),
            whatsapp_number: z.null(),
            status: z.string(),
            roles: z.string(),
            push_token: z.null(),
            name: z.string(),
            email: z.string(),
            gender: z.string(),
            citizenship_number: z.string(),
            citizenship_image_url: z.string(),
            address: z.string(),
            domicile: z.string(),
            date_of_birth: z.string(),
            birth_place: z.string(),
            is_default_otp: z.boolean(),
            country_code: z.string(),
            tnc_version: z.null(),
            tax_id_number: z.null(),
            external_id: z.string(),
            payroll_group_id: z.number(),
            blood_type: z.string(),
            marital_status: z.string(),
            religion: z.string(),
            resignation_date: z.null(),
            resignation_reason: z.null(),
            other_resignation_reason: z.null(),
            enable_instant_payment: z.boolean(),
            profile_onboard_completed: z.boolean(),
            hide_agent_onboard: z.boolean(),
            selfie_enrollment_id: z.null(),
            selfie_processing_id: z.null(),
            selfie_enrollment_attempt: z.number(),
            is_eligible_for_contract_signing: z.boolean(),
            team_leader_id: z.null(),
            id_card_url: z.null(),
            id_card_number: z.null(),
            id_card_updated_at: z.null(),
            approval_client_acc_id: z.number(),
            id: z.number(),
            client_id: z.number(),
            client_name: z.null(),
            client_logo_url: z.null(),
            created_at: z.string(),
            updated_at: z.null(),
            deleted_at: z.null(),
        });

    }
}